In [254]:
import pandas as pd
import numpy as np
import geopy as gp

In [8]:
data=pd.read_csv("Food_Inspections.csv")
data2=pd.read_csv("Business_Licenses.csv",sep=";")

In [19]:
license=data2.copy()

In [273]:
food=data.copy()

In [274]:
food[food["DBA Name"]=="LITTLE CAESAR ENTERPRISES"]

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,Results,Violations,Latitude,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards
10136,1610010,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Out of Business,NaN,41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
124689,1401619,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Pass w/ Conditions,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
126512,1401383,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
147927,1326572,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Pass,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
150795,1235156,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1820491.0,Restaurant,Risk 2 (Medium),6920 S ASHLAND AVE,CHICAGO,IL,60636.0,...,Out of Business,NaN,41.767893,-87.664019,"(-87.6640189682719, 41.76789331709745)",NaN,NaN,NaN,NaN,NaN
165944,537678,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Pass w/ Conditions,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
179091,481905,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1869512.0,Restaurant,Risk 2 (Medium),2024 E 95TH ST,CHICAGO,IL,60617.0,...,Pass w/ Conditions,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.722591,-87.574291,"(-87.57429097892624, 41.722591468010535)",NaN,NaN,NaN,NaN,NaN
181067,289309,LITTLE CAESAR ENTERPRISES,LITTLE CAESAR ENTERPRISES,1820491.0,Restaurant,Risk 2 (Medium),6920 S ASHLAND AVE,CHICAGO,IL,60636.0,...,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.767893,-87.664019,"(-87.6640189682719, 41.76789331709745)",NaN,NaN,NaN,NaN,NaN

In [307]:
# Find all columns with at least one null value
null_cols=np.sum(food.isnull() , axis=0)
null_cols[null_cols>0]

Series([], dtype: int64)

In [276]:
# The columns Historical Wards 2003-2015 , Zip Codes , Community Areas , Census Tracts and Ward are all empty. So we drop them

In [277]:
food.drop(columns=["Historical Wards 2003-2015","Zip Codes", "Community Areas", "Census Tracts", "Wards"],axis=1,inplace=True)

In [278]:
food["Zip"].value_counts().head(1).index
# Most common zipcode is 60614 , so we fill the null values with it
food["Zip"].fillna(60614,inplace=True)

In [279]:
food[food.State.isnull() & food.City.isnull()]["Address"].unique()
# All Null values in State and City are in Chicago ( checked with the respective adresses)

array(['636 N RACINE AVE ', '1438 W CORTLAND ST ', '500 N MILWAUKEE AVE ',
       '506 N Milwaukee AVE '], dtype=object)

In [280]:
food[food.State.isnull() & ~food.City.isnull()]["City"].unique()
# Null values in State with a known city are all in Chicago

array(['CHICAGO'], dtype=object)

In [281]:
food[(food.City.isnull()) & (food["State"]!="IL")]["Address"].unique()
# All Null values in City are in Chicago ( checked with the respective adresses)

array(['636 N RACINE AVE ', '1438 W CORTLAND ST ', '500 N MILWAUKEE AVE ',
       '506 N Milwaukee AVE '], dtype=object)

In [282]:
food["State"].fillna("IL", inplace=True)
food=food[food["State"]=="IL"]
food["City"].fillna("Chicago", inplace=True)

In [283]:
food[food["City"]!="CHICAGO"]["City"].unique()
# All these values are either typos for Chicago or Chicago suburbs (checked by zip code), so we keep them

array(['Chicago', 'SCHAUMBURG', 'CHICAGO.', 'CHESTNUT STREET',
       'CHICAGOCHICAGO', 'chicago', 'ROSEMONT', 'HIGHLAND PARK',
       'CALUMET CITY', 'NILES NILES', '312CHICAGO', 'ELK GROVE VILLAGE',
       'SKOKIE', 'EVANSTON', 'CCHICAGO', 'BANNOCKBURNDEERFIELD',
       'OAK PARK', 'ELMHURST', 'BLOOMINGDALE', 'CHicago', 'CICERO',
       'Norridge', 'CHCHICAGO', 'JUSTICE', 'LOMBARD', 'EAST HAZEL CREST',
       'COUNTRY CLUB HILLS', 'STREAMWOOD', 'INACTIVE', 'OLYMPIA FIELDS',
       'alsip', 'MAYWOOD', 'CHARLES A HAYES', 'WORTH', 'EVERGREEN PARK',
       'ALSIP', 'ALGONQUIN', 'LANSING', 'WHEATON', 'WILMETTE',
       'WADSWORTH', 'CHICAGOHICAGO', 'PLAINFIELD', 'PALOS PARK',
       'BRIDGEVIEW', 'LAKE BLUFF', 'SCHILLER PARK', 'BEDFORD PARK',
       'CHCICAGO', 'CHICAGOI', 'TINLEY PARK', 'SUMMIT', 'CHICAGO HEIGHTS',
       'WESTMONT', 'BOLINGBROOK', 'OOLYMPIA FIELDS', 'BERWYN',
       'DES PLAINES', 'LAKE ZURICH', 'BURNHAM', 'OAK LAWN', 'BLUE ISLAND',
       'GLENCOE', 'BROADVIEW', 'FRANKFORT', 'NAPERVILLE', 'Maywood'],
      dtype=object)

In [285]:
Illinois_zipcode=(60001,62999)
suburbs_zipcode=food[food["City"]!="CHICAGO"]["Zip"].unique()
# All the suburbs are within the Illinois zipcode range
all(Illinois_zipcode[0]<=city_zipcode<=Illinois_zipcode[1] for city_zipcode in suburbs_zipcode)

True

In [286]:
# Fill the null location values with default Chicago location
default_lat=41.85003
default_long=-87.65005
default_location='(-87.65005,41.85003)'
food["Latitude"].fillna(default_lat,inplace=True)
food["Longitude"].fillna(default_long,inplace=True)
food["Location"].fillna(default_location,inplace=True)

In [287]:
# we extract the business with null license ID
unlicensed=food[food["License #"].isnull()]["DBA Name"].unique()
# we check if they exist in the license database
for i in unlicensed:
    print(license[license["DOING BUSINESS AS NAME"]==i]["LICENSE ID"].unique())
# Some have none, some have many, and there are 17 null values in total, so we simply drop them
food=food[~food["License #"].isnull()]

[2616237]
[1776100 2009368 1201355 1875987 1451201 1451202 1309168 1552211 1653864
 1653863 1309169 1552210 1201354 2009367 1776099 1875988]
[]
[2094468 2608044]
[]
[]

In [288]:
# For the null values in Violations, we will just replace them with "0. None reported" since the violations are numbered
food["Violations"].fillna("0. None Reported", inplace=True)

In [289]:
fvc=food["Facility Type"].value_counts()
fvc[fvc>20]
##### Might be interesting to set outliers to other

Restaurant                           129903
Grocery Store                         24854
School                                12082
Children's Services Facility           3025
Bakery                                 2856
Daycare (2 - 6 Years)                  2687
Daycare Above and Under 2 Years        2337
Long Term Care                         1337
Catering                               1190
Mobile Food Dispenser                   867
Liquor                                  856
Daycare Combo 1586                      746
Mobile Food Preparer                    623
Golden Diner                            562
Hospital                                545
Wholesale                               535
TAVERN                                  282
Daycare (Under 2 Years)                 249
Special Event                           206
Shared Kitchen User (Long Term)         197
BANQUET HALL                            147
GAS STATION                             120
Mobile Prepared Food Vendor             111
Shared Kitchen                          109
KIOSK                                   105
Shelter                                  97
CHARTER SCHOOL                           73
LIVE POULTRY                             67
BANQUET                                  63
GROCERY/RESTAURANT                       54
Navy Pier Kiosk                          54
Mobile Frozen Desserts Vendor            52
DAYCARE                                  49
Daycare (2 Years)                        47
STADIUM                                  44
PRIVATE SCHOOL                           42
Shared Kitchen User (Short Term)         41
STORE                                    40
RESTAURANT/BAR                           38
ROOFTOP                                  37
CONVENIENCE                              37
CONVENIENCE STORE                        37
CAFETERIA                                36
ICE CREAM SHOP                           36
1023 CHILDERN'S SERVICES FACILITY        33
convenience store                        29
CHURCH KITCHEN                           28
1023-CHILDREN'S SERVICES FACILITY        27
CULINARY SCHOOL                          27
Pop-Up Establishment Host-Tier II        26
COMMISSARY                               26
CHURCH                                   26
RESTAURANT/GROCERY STORE                 26
ROOF TOPS                                24
MOBILE DESSERTS VENDOR                   22
RESTAURANT/GAS STATION                   22
Grocery & Restaurant                     21
tavern                                   21
NURSING HOME                             21
Name: Facility Type, dtype: int64

In [290]:
# For the null values in Facility Type, we will just replace them with "Unspecified"
food["Facility Type"].fillna("Unspecified", inplace=True)

In [291]:
food[food["Risk"]=="All"]
# 30 entries are marked as Risk : ALL . As we don't know the meaning of it and that those entries contain many null values,
# We choose to drop these entries
food=food[food["Risk"]!="All"]

In [292]:
food[food["Risk"].isnull()]["Inspection ID"].count()
# 72 entries in Risk are null, since there is no appropiate way to impute them, we choose to drop them
food=food[~food["Risk"].isnull()]

In [299]:
food.columns

Index(['Inspection ID', 'DBA Name', 'AKA Name', 'License #', 'Facility Type',
       'Risk', 'Address', 'City', 'State', 'Zip', 'Inspection Date',
       'Inspection Type', 'Results', 'Violations', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [303]:
# The null values in AKA Name can be replaced with their correspending BDA name
rows_to_impute=food[food["AKA Name"].isnull()].index
food.loc[rows_to_impute,"AKA Name"]=food.loc[rows_to_impute,"DBA Name"]

In [306]:
# There is one nul value for Inspection type, we drop it
food=food[~food["Inspection Type"].isnull()]

In [308]:
food.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194781 entries, 0 to 194903
Data columns (total 17 columns):
Inspection ID      194781 non-null int64
DBA Name           194781 non-null object
AKA Name           194781 non-null object
License #          194781 non-null float64
Facility Type      194781 non-null object
Risk               194781 non-null object
Address            194781 non-null object
City               194781 non-null object
State              194781 non-null object
Zip                194781 non-null float64
Inspection Date    194781 non-null object
Inspection Type    194781 non-null object
Results            194781 non-null object
Violations         194781 non-null object
Latitude           194781 non-null float64
Longitude          194781 non-null float64
Location           194781 non-null object
dtypes: float64(4), int64(1), object(12)
memory usage: 26.7+ MB

## From here I want to see if I can do better if I merge first

In [310]:
food2=data.copy()
food2.head(5)

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,Results,Violations,Latitude,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards
0,2320519,SALAM RESTAURANT,SALAM RESTAURANT,2002822.0,Restaurant,Risk 1 (High),4634-4636 N KEDZIE AVE,CHICAGO,IL,60625.0,...,Pass,NaN,41.965719,-87.708538,"(-87.70853756167853, 41.965719017423005)",NaN,NaN,NaN,NaN,NaN
1,2320443,JORDAN DISCOUNT,JORDAN DISCOUNT,2694525.0,Grocery Store,Risk 3 (Low),5254 W MADISON ST,CHICAGO,IL,60644.0,...,Pass,NaN,41.880455,-87.757290,"(-87.75728976536573, 41.88045497430518)",NaN,NaN,NaN,NaN,NaN
2,2320451,PRETTY COOL ICE CREAM,PRETTY COOL ICE CREAM,2616833.0,Restaurant,Risk 1 (High),2353 N CALIFORNIA AVE,CHICAGO,IL,60647.0,...,Pass,37. FOOD PROPERLY LABELED; ORIGINAL CONTAINER ...,41.924363,-87.697255,"(-87.69725539567338, 41.92436282156778)",NaN,NaN,NaN,NaN,NaN
3,2320388,BOMBASTIC CAFE,BOMBASTIC CAFE,2678198.0,Restaurant,Risk 2 (Medium),3732 N SOUTHPORT AVE,CHICAGO,IL,60613.0,...,Fail,"53. TOILET FACILITIES: PROPERLY CONSTRUCTED, S...",41.949883,-87.664242,"(-87.6642417785868, 41.94988264936109)",NaN,NaN,NaN,NaN,NaN
4,2320389,"ALL THINGS ARE POSSIBLE FOR KIDS, INC.","ALL THINGS ARE POSSIBLE FOR KIDS, INC.",2215965.0,Children's Services Facility,Risk 1 (High),4014 W CHICAGO AVE,CHICAGO,IL,60651.0,...,Pass,54. GARBAGE & REFUSE PROPERLY DISPOSED; FACILI...,41.895468,-87.726665,"(-87.7266648149535, 41.89546788877342)",NaN,NaN,NaN,NaN,NaN

In [311]:
fl=pd.merge(food2, license, how="left",left_on="License #", right_on="LICENSE ID")
fl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194904 entries, 0 to 194903
Data columns (total 61 columns):
Inspection ID                        194904 non-null int64
DBA Name                             194904 non-null object
AKA Name                             192453 non-null object
License #                            194887 non-null float64
Facility Type                        190128 non-null object
Risk                                 194832 non-null object
Address                              194904 non-null object
City                                 194766 non-null object
State                                194862 non-null object
Zip                                  194854 non-null float64
Inspection Date                      194904 non-null object
Inspection Type                      194903 non-null object
Results                              194904 non-null object
Violations                           143211 non-null object
Latitude                             194222 non-null float64
Longitude                            194222 non-null float64
Location                             194222 non-null object
Historical Wards 2003-2015_x         0 non-null float64
Zip Codes_x                          0 non-null float64
Community Areas_x                    0 non-null float64
Census Tracts_x                      0 non-null float64
Wards_x                              0 non-null float64
ID                                   143326 non-null object
LICENSE ID                           143326 non-null float64
ACCOUNT NUMBER                       143326 non-null float64
SITE NUMBER                          143326 non-null float64
LEGAL NAME                           143326 non-null object
DOING BUSINESS AS NAME               143326 non-null object
ADDRESS                              143326 non-null object
CITY                                 143326 non-null object
STATE                                143326 non-null object
ZIP CODE                             143168 non-null object
WARD                                 142943 non-null float64
PRECINCT                             134427 non-null float64
WARD PRECINCT                        143000 non-null object
POLICE DISTRICT                      134991 non-null float64
LICENSE CODE                         143326 non-null float64
LICENSE DESCRIPTION                  143326 non-null object
BUSINESS ACTIVITY ID                 137540 non-null object
BUSINESS ACTIVITY                    137540 non-null object
LICENSE NUMBER                       143326 non-null float64
APPLICATION TYPE                     143326 non-null object
APPLICATION CREATED DATE             125870 non-null object
APPLICATION REQUIREMENTS COMPLETE    138584 non-null object
PAYMENT DATE                         137325 non-null object
CONDITIONAL APPROVAL                 143326 non-null object
LICENSE TERM START DATE              142754 non-null object
LICENSE TERM EXPIRATION DATE         143310 non-null object
LICENSE APPROVED FOR ISSUANCE        138163 non-null object
DATE ISSUED                          143326 non-null object
LICENSE STATUS                       143326 non-null object
LICENSE STATUS CHANGE DATE           5754 non-null object
SSA                                  46927 non-null float64
LATITUDE                             141660 non-null float64
LONGITUDE                            141660 non-null float64
LOCATION                             141660 non-null object
Community Areas_y                    140063 non-null float64
Historical Wards 2003-2015_y         140063 non-null float64
Zip Codes_y                          141660 non-null object
Census Tracts_y                      141648 non-null float64
Wards_y                              140063 non-null float64
dtypes: float64(24), int64(1), object(36)
memory usage: 92.2+ MB

In [312]:
fl[(fl["Latitude"].isnull())&~(fl["LATITUDE"].isnull())]
# We can impute the values

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,Community Areas_y,Historical Wards 2003-2015_y,Zip Codes_y,Census Tracts_y,Wards_y
970,2290928,SCHWAB REHAB HOSPITAL&CARE NET,SCHWAB REHAB HOSPITAL&CARE NET,2205586.0,Hospital,Risk 1 (High),1401 S CALIFORNIA AVE,CHICAGO,IL,60608.0,...,NaN,NaN,41.862520,-87.695645,"(41.86251966597367, -87.69564453384106)",30.0,11.0,"14,920",16.0,23.0
2686,2229372,RICE THAI CAFE,RICE THAI CAFE,2589016.0,NaN,NaN,211`7 W FARRAGUT AVE,CHICAGO,IL,60625.0,...,NaN,54.0,42.004881,-87.661011,"(42.00488091989163, -87.66101071134382)",10.0,3.0,"21,853",47.0,5.0
3442,2181528,MAGO GRILL & CANTINA,MAGO GRILL & CANTINA,2423995.0,Restaurant,Risk 1 (High),1010 S DELANO CT,CHICAGO,IL,60605.0,...,NaN,NaN,41.869464,-87.632854,"(41.86946441129826, -87.63285448774887)",38.0,48.0,"14,917",12.0,26.0
5630,2078297,CHARTWELLS,MANSUETO HIGH SCHOOL,2549059.0,HIGH SCHOOL KITCHEN,Risk 1 (High),2911 W W 47TH ST,CHICAGO,IL,60632.0,...,NaN,NaN,41.808122,-87.697074,"(41.80812169070144, -87.69707374951754)",55.0,49.0,"22,248",85.0,8.0
7855,1966841,CAFFE ROM,CAFFE ROM,1847943.0,Restaurant,Risk 2 (Medium),400 E WATER ST,CHICAGO,IL,60601.0,...,NaN,NaN,41.886634,-87.617413,"(41.886633519398195, -87.61741342043217)",38.0,22.0,"14,309",580.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193218,98355,BAGONG TAON ORIENTAL MART,BAGONG TAON ORIENTAL MART,2014336.0,Grocery Store,Risk 3 (Low),3549 W IRVING PK. RD. RD,CHICAGO,IL,60618.0,...,NaN,NaN,41.953683,-87.717355,"(41.95368324175896, -87.7173554572528)",16.0,2.0,"21,538",325.0,12.0
193221,98335,BAGONG TAON ORIENTAL MART,BAGONG TAON ORIENTAL MART,2014336.0,Grocery Store,Risk 3 (Low),3549 W IRVING PK. RD. RD,CHICAGO,IL,60618.0,...,NaN,NaN,41.953683,-87.717355,"(41.95368324175896, -87.7173554572528)",16.0,2.0,"21,538",325.0,12.0
193869,158253,ARGENTINA FOODS,ARGENTINA FOODS,2009367.0,Grocery Store,Risk 2 (Medium),4500 S WOODS ST,CHICAGO,IL,60609.0,...,NaN,NaN,41.812105,-87.670072,"(41.81210515297724, -87.67007183351623)",59.0,53.0,"14,924",706.0,3.0
194066,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,NaN,NaN,41.981063,-87.845674,"(41.98106319707633, -87.84567441591551)",75.0,34.0,"22,243",64.0,29.0
194493,158272,ARGENTINA FOODS,ARGENTINA FOODS,2009367.0,Grocery Store,Risk 2 (Medium),4500 S WOODS ST,CHICAGO,IL,60609.0,...,NaN,NaN,41.812105,-87.670072,"(41.81210515297724, -87.67007183351623)",59.0,53.0,"14,924",706.0,3.0

In [313]:
null_cols=np.sum(license.isnull() , axis=0)
null_cols[null_cols>0]

LEGAL NAME                                4
DOING BUSINESS AS NAME                   75
CITY                                      3
STATE                                    12
ZIP CODE                                421
WARD                                  73443
PRECINCT                             105295
WARD PRECINCT                         73258
POLICE DISTRICT                       99854
BUSINESS ACTIVITY ID                 532936
BUSINESS ACTIVITY                    532936
LICENSE NUMBER                            1
APPLICATION CREATED DATE             757679
APPLICATION REQUIREMENTS COMPLETE     18307
PAYMENT DATE                          22004
LICENSE TERM START DATE                2684
LICENSE TERM EXPIRATION DATE             95
LICENSE APPROVED FOR ISSUANCE         48523
LICENSE STATUS CHANGE DATE           919946
SSA                                  730861
LATITUDE                              76704
LONGITUDE                             76704
LOCATION                              76704
Community Areas                       81731
Historical Wards 2003-2015            81604
Zip Codes                             76704
Census Tracts                         77643
Wards                                 81731
dtype: int64

In [314]:
fl[fl["LICENSE ID"].isnull()]

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,Community Areas_y,Historical Wards 2003-2015_y,Zip Codes_y,Census Tracts_y,Wards_y
1,2320443,JORDAN DISCOUNT,JORDAN DISCOUNT,2694525.0,Grocery Store,Risk 3 (Low),5254 W MADISON ST,CHICAGO,IL,60644.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2320388,BOMBASTIC CAFE,BOMBASTIC CAFE,2678198.0,Restaurant,Risk 2 (Medium),3732 N SOUTHPORT AVE,CHICAGO,IL,60613.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2320364,FIREWATER SALOON MOUNT GREENWOOD,FIREWATER SALOON MOUNT GREENWOOD,15956.0,Restaurant,Risk 1 (High),3908 W 111TH ST,CHICAGO,IL,60655.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2320354,AVLI RIVER NORTH,AVLI RIVER NORTH,2683658.0,Restaurant,Risk 3 (Low),700-702 N WELLS ST,CHICAGO,IL,60654.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2320439,TAQUERIA LA CIUDAD,TAQUERIA LA CIUDAD,2631346.0,Mobile Food Preparer,Risk 2 (Medium),3233-3237 W Cermak RD,CHICAGO,IL,60623.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194891,124352,RESURRECTION LIFE CENTER,RESURRECTION LIFE CENTER,57358.0,Long Term Care,Risk 1 (High),7435 W TALCOTT AVE,CHICAGO,IL,60631.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194895,164363,TOWN FOOD & LIQUOR,TOWN FOOD & LIQUOR,13826.0,Grocery Store,Risk 3 (Low),1813 W 63RD ST,CHICAGO,IL,60636.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194898,134239,BORNIQUEN RESTAURANT,BORNIQUEN RESTAURANT,32942.0,Restaurant,Risk 1 (High),1720 N CALIFORNIA AVE,CHICAGO,IL,60647.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194901,164336,White,White,26431.0,School,Risk 1 (High),1136 W 122nd St (12200S),CHICAGO,IL,60643.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194903,176291,"JOE'S BARBQUE, INC",JOE'S BARBQUE,18234.0,Restaurant,Risk 1 (High),4900 W MADISON ST,CHICAGO,IL,60644.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [315]:
license["BUSINESS ACTIVITY"].unique()

array([nan, 'Retail Sales of Perishable Foods',
       'Catering of Liquor From a Business Not Located In Chicago', ...,
       'Provide Animal Boarding Services | Provide Animal Day Care Services | Retail Sales of General Merchandise',
       "Retail Sales of General Merchandise | Buying and Reselling of Used Children's Products",
       'Rental of Musical Instruments | Instruction in Music for Both Children and Adults (Less Than 40% Children)'],
      dtype=object)

In [319]:
fl[(fl["Zip"].isnull()) & (~fl["ZIP CODE"].isnull())]

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,...,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION,Community Areas_y,Historical Wards 2003-2015_y,Zip Codes_y,Census Tracts_y,Wards_y
9453,1763245,EAT N RUN CHICKEN AND FISH,EAT N RUN CHICKEN AND FISH,2442868.0,Restaurant,Risk 1 (High),,NaN,IL,NaN,...,NaN,69.0,41.743903,-87.663129,"(41.743903369579925, -87.6631288234479)",70.0,18.0,"21,554",575.0,13.0
13423,1447538,I DREAM OF FALAFEL,I DREAM OF FALAFEL,2032750.0,NaN,Risk 1 (High),329 S FRANKLIN ST,NaN,IL,NaN,...,NaN,NaN,41.877351,-87.635043,"(41.87735119229724, -87.63504276859136)",38.0,48.0,"14,914",92.0,36.0
16296,1106878,FILIPINO AMERICAN COUNCIL,RIZAL CENTER,2225427.0,Golden Diner,Risk 1 (High),1332 W DRIVING PARK ROAD BSMT,NaN,IL,NaN,...,NaN,33.0,41.909454,-87.675796,"(41.9094539015706, -87.6757962173346)",25.0,24.0,"21,560",482.0,41.0
22512,598237,SPORT SERVICE SOLDIER FIELD/SUITE PANTRY D,SUITE PANTRY D,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS DR.,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
23176,525238,THE LUNCH MACHINE INC,NaN,2079077.0,Mobile Food Dispenser,Risk 2 (Medium),1319 W WILSON AVE,NaN,IL,NaN,...,12/29/2012,34.0,41.965212,-87.663260,"(41.96521193313759, -87.66326005651248)",31.0,37.0,"22,616",611.0,39.0
23288,525226,THE LUNCH MACHINE INC,NaN,2079077.0,Mobile Food Dispenser,Risk 2 (Medium),1319 W WILSON AVE,NaN,IL,NaN,...,12/29/2012,34.0,41.965212,-87.663260,"(41.96521193313759, -87.66326005651248)",31.0,37.0,"22,616",611.0,39.0
23338,525214,THE LUNCH MACHINE INC,NaN,2079077.0,Mobile Food Dispenser,Risk 2 (Medium),1319 W WILSON AVE,NaN,IL,NaN,...,12/29/2012,34.0,41.965212,-87.663260,"(41.96521193313759, -87.66326005651248)",31.0,37.0,"22,616",611.0,39.0
24022,335363,TISH'S TINY TOWN FOR TOTS CHI,TISH'S TINY TOWN FOR TOTS CHI,1887746.0,NaN,Risk 1 (High),2301 E 79TH ST,NaN,IL,NaN,...,NaN,49.0,41.751592,-87.568606,"(41.7515920243175, -87.56860603613539)",42.0,43.0,"21,202",507.0,37.0
24191,414066,OSCO DRUG #3632,OSCO DRUG #3632,2037183.0,Liquor,Risk 3 (Low),3630 N SOUTHPORT AVE,NaN,IL,NaN,...,NaN,27.0,41.948005,-87.664186,"(41.948004550829744, -87.66418623070139)",57.0,38.0,"21,186",724.0,25.0
42696,2222692,LEO'S FOOD AND LIQUOR,LEO'S LIQUOR,2535068.0,Liquor,Risk 3 (Low),4471 W LAWRENCE AVE,NaN,IL,NaN,...,NaN,NaN,41.967993,-87.740726,"(41.96799335620968, -87.74072634914224)",16.0,20.0,"21,869",362.0,38.0
45494,2200428,LEO'S FOOD AND LIQUOR,LEO'S LIQUOR,2535068.0,Liquor,Risk 3 (Low),4471 W LAWRENCE AVE,NaN,IL,NaN,...,NaN,NaN,41.967993,-87.740726,"(41.96799335620968, -87.74072634914224)",16.0,20.0,"21,869",362.0,38.0
73116,1977089,SUBWAY,NaN,1991157.0,Restaurant,Risk 2 (Medium),2184 N CLYBOURN BLDG,NaN,IL,NaN,...,NaN,NaN,41.921186,-87.664014,"(41.92118550519079, -87.6640136808923)",68.0,16.0,"21,190",210.0,11.0
99921,1562130,PARKWEST LIQUORS AND SMOKE SHOP,PARKWEST LIQUORS,2354157.0,Liquor,Risk 3 (Low),2570 N LINCOLN AVE,NaN,IL,NaN,...,NaN,35.0,41.928597,-87.653388,"(41.92859664532255, -87.65338817338453)",68.0,51.0,"21,190",769.0,34.0
100953,1375435,N AND A FOOD MART INC,NaN,1980101.0,Grocery Store,Risk 3 (Low),433 E 79TH STREET,NaN,IL,NaN,...,NaN,51.0,41.751030,-87.613649,"(41.75103049992091, -87.61364868855419)",40.0,31.0,"21,546",11.0,32.0
103290,1566296,PARKWEST LIQUORS AND SMOKE SHOP,PARKWEST LIQUORS,2354157.0,Liquor,Risk 3 (Low),2570 N LINCOLN AVE,NaN,IL,NaN,...,NaN,35.0,41.928597,-87.653388,"(41.92859664532255, -87.65338817338453)",68.0,51.0,"21,190",769.0,34.0
107986,1523196,BURGER KING #1310,BURGER KING,2232344.0,Restaurant,Risk 2 (Medium),2320-2322 S MICHIGAN AVE,NaN,IL,NaN,...,NaN,NaN,41.850454,-87.623891,"(41.850453739981155, -87.62389126353149)",34.0,48.0,"21,194",193.0,9.0
108206,1538026,FOSTER GROCERY AND DOLLAR PLUS,NaN,1992096.0,Grocery Store,Risk 3 (Low),3358 W FOSTER AVE,NaN,IL,NaN,...,NaN,NaN,41.975801,-87.713499,"(41.97580062815588, -87.71349867231145)",13.0,28.0,"21,849",167.0,38.0
126291,1396156,THINK SIMPLE FOODS,NaN,2308286.0,Restaurant,Risk 2 (Medium),141 W CHICAGO AVE,NaN,IL,NaN,...,NaN,NaN,41.896504,-87.632784,"(41.89650357363852, -87.6327844082446)",37.0,22.0,"4,446",670.0,11.0
129348,1228307,MCCORNICK PLACE,WEST WAREHOUSE / WBI - 122,1932251.0,Restaurant,Risk 1 (High),2301 S INDIANA,NaN,IL,NaN,...,NaN,NaN,41.851047,-87.622093,"(41.85104667463312, -87.62209308455373)",34.0,48.0,"21,194",193.0,10.0
130760,1396011,THINK SIMPLE FOODS,NaN,2308286.0,Restaurant,Risk 2 (Medium),141 W CHICAGO AVE,NaN,IL,NaN,...,NaN,NaN,41.896504,-87.632784,"(41.89650357363852, -87.6327844082446)",37.0,22.0,"4,446",670.0,11.0
131894,1228306,MCCORMICK PLACE,KIOSK HOLDING UNIT AREA,1932251.0,Restaurant,Risk 1 (High),2301 S INDIANA AVE.,NaN,IL,NaN,...,NaN,NaN,41.851047,-87.622093,"(41.85104667463312, -87.62209308455373)",34.0,48.0,"21,194",193.0,10.0
133170,1115029,SPORT SERVICE SOLDIER FIELD,SUITE PANTRY B,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS DR.,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
136713,1115030,SPORT SERVICE SOLDIER FIELD /SUITE PANTRY C,SUITE PANTRY C,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
137268,1361108,SPORT SERVICE SOLDIER FIELD/SUITE PANTRY D,SUITE PANTRY D,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS DR.,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
144378,1114725,BURGER KING #1310,BURGER KING,2232344.0,Restaurant,Risk 2 (Medium),2320-2322 S MICHIGAN AVE,NaN,IL,NaN,...,NaN,NaN,41.850454,-87.623891,"(41.850453739981155, -87.62389126353149)",34.0,48.0,"21,194",193.0,9.0
161858,679984,OSCO DRUG #3632,OSCO DRUG #3632,2137471.0,Liquor,Risk 3 (Low),3630 N SOUTHPORT AVE,NaN,IL,NaN,...,NaN,27.0,41.948005,-87.664186,"(41.948004550829744, -87.66418623070139)",57.0,38.0,"21,186",724.0,25.0
172727,598235,SPORT SERVICE SOLDIER FIELD,SUITE PANTRY B,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS DR.,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
172771,598236,SPORT SERVICE SOLDIER FIELD /SUITE PANTRY C,SUITE PANTRY C,1354323.0,Restaurant,Risk 2 (Medium),1410 S MUSEUM CAMPUS,NaN,IL,NaN,...,NaN,NaN,41.862628,-87.615031,"(41.862628294037634, -87.61503109411332)",34.0,48.0,"14,913",374.0,10.0
176288,525253,THE LUNCH MACHINE INC,NaN,2079077.0,Mobile Food Dispenser,Risk 2 (Medium),1319 W WILSON AVE,NaN,IL,NaN,...,12/29/2012,34.0,41.965212,-87.663260,"(41.96521193313759, -87.66326005651248)",31.0,37.0,"22,616",611.0,39.0
178883,391371,GOLDEN HOUSE RESTAURANT,NaN,1443483.0,Restaurant,Risk 1 (High),4742-44 N RACINE AVE,NaN,IL,NaN,...,NaN,34.0,41.968491,-87.659816,"(41.968490719713, -87.65981645066375)",31.0,37.0,"22,616",611.0,39.0
178942,525228,THE LUNCH MACHINE INC,NaN,2079077.0,Mobile Food Dispenser,Risk 2 (Medium),1319 W WILSON AVE,NaN,IL,NaN,...,12/29/2012,34.0,41.965212,-87.663260,"(41.96521193313759, -87.66326005651248)",31.0,37.0,"22,616",611.0,39.0
180901,525229,GOLDEN HOUSE RESTAURANT,NaN,1443483.0,Restaurant,Risk 1 (High),4742-44 N RACINE AVE,NaN,IL,NaN,...,NaN,34.0,41.968491,-87.659816,"(41.968490719713, -87.65981645066375)",31.0,37.0,"22,616",611.0,39.0
181128,413369,I DREAM OF FALAFEL,I DREAM OF FALAFEL,2032750.0,NaN,Risk 1 (High),329 S FRANKLIN ST,NaN,IL,NaN,...,NaN,NaN,41.877351,-87.635043,"(41.87735119229724, -87.63504276859136)",38.0,48.0,"14,914",92.0,36.0
181135,419311,OSCO DRUG #3632,OSCO DRUG #3632,2037183.0,Liquor,Risk 3 (Low),3630 N SOUTHPORT AVE,NaN,IL,NaN,...,NaN,27.0,41.948005,-87.664186,"(41.948004550829744, -87.66418623070139)",57.0,38.0,"21,186",724.0,25.0
181351,419250,OSCO DRUG #3632,OSCO DRUG #3632,2037183.0,Liquor,Risk 3 (Low),3630 N SOUTHPORT AVE,NaN,IL,NaN,...,NaN,27.0,41.948005,-87.664186,"(41.948004550829744, -87.66418623070139)",57.0,38.0,"21,186",724.0,25.0
193238,63277,SUN FOOD MART,SUN FOOD MART,2009479.0,Grocery Store,Risk 3 (Low),3601 W CERMAK RD,NaN,IL,NaN,...,NaN,NaN,41.851553,-87.715059,"(41.85155346052472, -87.715059286164)",32.0,14.0,"21,569",754.0,28.0
194233,67807,SUN FOOD MART,SUN FOOD MART,2009479.0,Grocery Store,Risk 3 (Low),3601 W CERMAK RD,NaN,IL,NaN,...,NaN,NaN,41.851553,-87.715059,"(41.85155346052472, -87.715059286164)",32.0,14.0,"21,569",754.0,28.0

In [329]:
license[["LICENSE TERM START DATE","BUSINESS ACTIVITY","LICENSE TERM EXPIRATION DATE"]].sample(5)

       LICENSE TERM START DATE BUSINESS ACTIVITY LICENSE TERM EXPIRATION DATE
975357              07/06/2011               NaN                   07/15/2013
194580              02/16/2004               NaN                   02/15/2005
165858              07/16/2014     Hair Services                   07/15/2016
685733              06/13/2008               NaN                   11/15/2009
528852              11/16/2005               NaN                   11/15/2006

In [330]:
license["BUSINESS ACTIVITY"].value_counts()

Retail Sales of Perishable Foods                                                                                                                                                                                                                                                                                                                                            128482
Retail Sale of Tobacco                                                                                                                                                                                                                                                                                                                                                       40514
Consumption of Liquor on Premises                                                                                                                                                                                                                                                                                                                                            30570
Tavern - Consumption of Liquor on Premise                                                                                                                                                                                                                                                                                                                                    16782
Retail Sales of Packaged Liquor                                                                                                                                                                                                                                                                                                                                              14105
                                                                                                                                                                                                                                                                                                                                                                             ...
Retail Sales of General Merchandise and Non-Perishable Food | Sale of Furniture | Retail Sales of Clothing / Accessories / Shoes                                                                                                                                                                                                                                                 1
After School Program / Tutoring Children Under 18 Years of Age | Supervision of, and Care for, Children Under 2 Years of Age, During the Day Between 6am-9pm | Supervision of, and Care for, Children 2-6 Years of Age, During the Day Between 6am-9pm With Before and After School Programs | Supervision of, and Care for Children, During the Evening Between 9pm-6am         1
Laundry Service | Retail Sales of Laundry Cleaning Products | Laundromat - Self Service | Vending Machines (Sodas, Candy, Chips)                                                                                                                                                                                                                                                 1
Shipping / Printing Services | Retail Sales of General Merchandise | Financial Services                                                                                                                                                                                                                                                                                          1
Retail Sales of General Merchandise and Non-Perishable Food | Retail Sales of General Merchandise | Tanning Facility                                                                                                                                                                                                                                                             1
Name: BUSINESS ACTIVITY, Length: 4643, dtype: int64

In [ ]:
#### For now, license database can be used to impute location and zipcode. Do we really need it ?
#### When merged on License ID, 50K of the 200K in food are not matched, should we focus only on the rest?
#### Then we can use business activity and License date to classify by activity and run time series
#### (e.g frequency )